server.port=8080
<<<<<<< HEAD
# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://chamathdew2026_db_user:rF4UZLOebPdMB9mi@oceanviewcluster.xefsc8q.mongodb.net/OceanViewResort?retryWrites=true&w=majority
=======
spring.data.mongodb.uri=mongodb+srv://chamathdofficial_db_user:chamathdew2002@oceanview.wvjeaiy.mongodb.net/oceanview_resort?retryWrites=true&w=majority&appName=OceanView
spring.data.mongodb.auto-index-creation=true
>>>>>>> origin/main

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chamathd2002@gmail.com
<<<<<<< HEAD
spring.mail.password=#Burnitdown2002#
=======
spring.mail.password=burnitdown2002
>>>>>>> origin/main
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
