server.port=8080
# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://chamathdew2026_db_user:rF4UZLOebPdMB9mi@oceanviewcluster.xefsc8q.mongodb.net/OceanViewResort?retryWrites=true&w=majority

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chamathd2002@gmail.com
spring.mail.password=#Burnitdown2002#
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
